config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root :to => 'page#connect'
  end

  root :to => 'page#landing_page'

  get 'page/index'
  get 'page/trip_progress'
  get 'page/trip_summary'
  get 'page/traffic_light'
  get 'page/sign_adherence'
  get 'page/speed'
  get 'page/progress'
  get 'page/rewards'
  get 'page/rewards_information'
  get 'page/carwash_voucher'
  get 'page/fuel_voucher'
  get 'page/board'
  get 'page/connect'
  get 'page/landing_page'

  resources :drive_data
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drive_datum.rb
class DriveDatum < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drive_data_controller.rb
class DriveDataController < ApplicationController
  before_action :set_drive_datum, only: [:show, :edit, :update, :destroy]

  # GET /drive_data
  # GET /drive_data.json
  def index
    @drive_data = DriveDatum.all
  end

  # GET /drive_data/1
  # GET /drive_data/1.json
  def show
  end

  # GET /drive_data/new
  def new
    @drive_datum = DriveDatum.new
  end

  # GET /drive_data/1/edit
  def edit
  end

  # POST /drive_data
  # POST /drive_data.json
  def create
    @drive_datum = DriveDatum.new(drive_datum_params)

    respond_to do |format|
      if @drive_datum.save
        format.html { redirect_to @drive_datum, notice: 'Drive datum was successfully created.' }
        format.json { render :show, status: :created, location: @drive_datum }
      else
        format.html { render :new }
        format.json { render json: @drive_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drive_data/1
  # PATCH/PUT /drive_data/1.json
  def update
    respond_to do |format|
      if @drive_datum.update(drive_datum_params)
        format.html { redirect_to @drive_datum, notice: 'Drive datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @drive_datum }
      else
        format.html { render :edit }
        format.json { render json: @drive_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drive_data/1
  # DELETE /drive_data/1.json
  def destroy
    @drive_datum.destroy
    respond_to do |format|
      format.html { redirect_to drive_data_url, notice: 'Drive datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drive_datum
      @drive_datum = DriveDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drive_datum_params
      params.require(:drive_datum).permit(:user_id, :stats, :start_time, :end_time, :start_loc, :end_loc)
    end
end

app/controllers/page_controller.rb
require_dependency 'helper.rb'

class PageController < ApplicationController
  include Helper
  def index

  end

  def trip_summary
    # stats = [["traffic_light", [-33.881842, 151.20396]], ["sign_adherence", [-33.879237, 151.205443]]].to_json
    @trip_data = {
      stats: [
        {
        violation: "traffic_light",
        location: [-33.881842, 151.20396]
        },
        {
          violation: "sign_adherence",
          location: [-33.879237, 151.205443]
        },
      ],
      start_time: "2017-07-29 06:11:00",
      end_time: "2017-07-29 06:38:00",
      start_loc: [-33.884369, 151.175759],
      end_loc: [-33.877611, 151.221725]
    }
    d = DateTime.now
    end_time = [@trip_data[:end_time][11..13].to_i, @trip_data[:end_time][14..16].to_i, @trip_data[:end_time][17..19].to_i]
    start_time = [@trip_data[:start_time][11..13].to_i, @trip_data[:start_time][14..16].to_i, @trip_data[:start_time][17..19].to_i]
    total_sec = Helper.total_sec(end_time) - Helper.total_sec(start_time)
    @time = Helper.time_formatter(total_sec)
    @counter = Helper.violation_counter(@trip_data[:stats])
    @score = Helper.count_deduction_drive(@trip_data[:stats])
    @drive_datum = DriveDatum.new(@trip_data)
    @drive_datum[:user_id] = current_user.id
    @drive_datum[:month] = Helper.get_month_year(@trip_data)
    @drive_datum.save
    @distance = Helper.distance(@drive_datum[:start_loc], @drive_datum[:end_loc])
  end

  def traffic_light
    @month_labels = Helper.get_last_half_year.to_json
    @deduction_points = Helper.get_traffic_light_deductions(current_user.id)
    @deductions = Helper.get_deductions(current_user.id)
    @month_ranges = Helper.get_month_range_names
  end

  def sign_adherence
    @month_labels = Helper.get_last_half_year.to_json
    @deduction_points = Helper.get_sign_adherence_deductions(current_user.id)
    @deductions = Helper.get_deductions(current_user.id)
    @month_ranges = Helper.get_month_range_names
  end

  def speed
    @month_labels = Helper.get_last_half_year.to_json
    @deduction_points = Helper.get_speed_deductions(current_user.id)
    @deductions = Helper.get_deductions(current_user.id)
    @month_ranges = Helper.get_month_range_names
  end

  def progress
    if current_user
      @good_drives = Helper.count_good_drives(current_user)
      @deductions = Helper.get_deductions(current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  def rewards
    if current_user
      @score = Helper.get_monthly_score(Date.today.to_s[0..6], current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  def board
    @users = []
    # @sorted_user = []
    #
    # User.all.each do |user|
    #   if @sorted_user.length == 0
    #     @sorted_user.push(user)
    #   else
    #     @sorted_user.each_with_index do |item, index|
    #       if user <= item
    #
    #       end
    #     end
    #   end
    #     @sorted_user.push(user)
    # end

    User.all.each do |user|
      array = []
      array << user
      array << Helper.get_monthly_score(Date.today.to_s[0..6], user.id)
      @users << array
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drive_data_helper.rb
module DriveDataHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/drive_data/edit.html.erb
<h1>Editing Drive Datum</h1>

<%= render 'form', drive_datum: @drive_datum %>

<%= link_to 'Show', @drive_datum %> |
<%= link_to 'Back', drive_data_path %>

app/views/drive_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drive Data</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Stats</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Start loc</th>
      <th>End loc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drive_data.each do |drive_datum| %>
      <tr>
        <td><%= drive_datum.user %></td>
        <td><%= drive_datum.stats %></td>
        <td><%= drive_datum.start_time %></td>
        <td><%= drive_datum.end_time %></td>
        <td><%= drive_datum.start_loc %></td>
        <td><%= drive_datum.end_loc %></td>
        <td><%= link_to 'Show', drive_datum %></td>
        <td><%= link_to 'Edit', edit_drive_datum_path(drive_datum) %></td>
        <td><%= link_to 'Destroy', drive_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drive Datum', new_drive_datum_path %>

app/views/drive_data/new.html.erb
<h1>New Drive Datum</h1>

<%= render 'form', drive_datum: @drive_datum %>

<%= link_to 'Back', drive_data_path %>

app/views/drive_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @drive_datum.user %>
</p>

<p>
  <strong>Stats:</strong>
  <%= @drive_datum.stats %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @drive_datum.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @drive_datum.end_time %>
</p>

<p>
  <strong>Start loc:</strong>
  <%= @drive_datum.start_loc %>
</p>

<p>
  <strong>End loc:</strong>
  <%= @drive_datum.end_loc %>
</p>

<%= link_to 'Edit', edit_drive_datum_path(@drive_datum) %> |
<%= link_to 'Back', drive_data_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vibit</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
    <link rel="stylesheet" type="text/css" href="https://js.cit.api.here.com/v3/3.0/mapsjs-ui.css" />
    <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-core.js"></script>
    <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-service.js"></script>
    <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-ui.js"></script>
    <script type="text/javascript" src="https://js.cit.api.here.com/v3/3.0/mapsjs-mapevents.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="background">
      <!-- <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Progress", page_progress_path %></li>
      <li><%= link_to "Rewards", page_rewards_path %></li>
      <li><%= link_to "Board", page_board_path %></li>
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>
      <br> -->

      <%= yield %>
      <%= render 'components/nav' %>
    </div>
  </body>
</html>

app/views/page/board.html.erb
<div class="top-nav-with-info">
  <div class="back"></div>
  <div class="heading text-center">
    <span class="white-text thin-text">RANK</span>
  </div>
  <div class="back flex-center">
    <a href="/"><%#= image_tag "info.svg", height: '15px' %></a>
  </div>
</div>

<div class="rank-container">
  <div class="white-box text-center">FRIENDS</div>
  <div class="orange-box text-center">STATE</div>
  <div class="rank-box">

    <% @users.each_with_index do |user, index| %>
      <div class="individual-box">
        <div class="padding">
          <strong>#<%= index + 1 %></strong>
           - <%= user[0].email %>
          
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/page/carwash_voucher.html.erb
<div class="full-white-bg">
  <%= render 'components/white_topnav', title: "CARWASH VOUCHERS"%>
  <div class="text-center">
    <span class="large-text">SCAN AT COUNTER</span><br><br>
    <%= image_tag "qrcode.svg"%>
  </div>
  <br>
  <div class="continue-button text-center">
    <%= link_to "USE VOUCHER".html_safe, root_path, :class=>"btn orange-button btn-round-lg btn-lg continue"%>
  </div>
  <br>
</div>

app/views/page/connect.html.erb
<div>
  <div class="title text-center">
    <h1 class="white" id="start-title">ViBit</h1>
  </div>

  <div class="subtitle text-center">
    <h5 class="white">SHAPING TOMORROW'S DRIVERS</h5>
  </div>

  <div class="flex-center wheel-image">
    <%= image_tag "connect.svg" %>
  </div>

  <div class="start-button end-button text-center">
    <%= link_to "Connect to ViBit".html_safe, page_index_path, :class=>"white btn btn-primary btn-round-lg white-button btn-lg start"%>
  </div>

</div>

app/views/page/fuel_voucher.html.erb
<div class="full-white-bg">
  <%= render 'components/white_topnav', title: "FUEL VOUCHER"%>
  <div class="text-center">
    <span class="large-text">SCAN AT COUNTER</span><br><br>
    <%= image_tag "qrcode.svg"%>
  </div>
  <br>
  <div class="continue-button text-center">
    <%= link_to "USE VOUCHER".html_safe, page_rewards_path, :class=>"btn orange-button btn-round-lg btn-lg continue"%>
  </div>
  <br>
</div>

app/views/page/index.html.erb
<div>
  <div class="title text-center">
    <h1 class="white" id="start-title">ViBit</h1>
  </div>

  <div class="subtitle text-center">
    <h5 class="white">SHAPING TOMORROW'S DRIVERS</h5>
  </div>

  <div class="flex-center wheel-image">
    <%= image_tag "wheel.svg" %>
  </div>

  <div class="start-button text-center">
    <%= link_to "START TRIP".html_safe, page_trip_progress_path, :class=>"white btn btn-primary btn-round-lg white-button btn-lg start"%>
  </div>

  <div class="switch-account text-center">
    <%= link_to('Switch Accounts', destroy_user_session_path, method: :delete) %>
    <%#= link_to "Switch Accounts", new_user_session_path %>
  </div>
</div>

app/views/page/landing_page.html.erb
<div>
  <div class="title text-center">
    <h1 class="white" id="start-title">ViBit</h1>
  </div>

  <div class="subtitle text-center">
    <h5 class="white">SHAPING TOMORROW'S DRIVERS</h5>
  </div>

  <div class="owl-carousel end-button">
    <div>
      <div class="flex-center wheel-image">
        <%= image_tag "route.svg" %>
      </div>
      <div class="white text-center">
        <h3>Keep track of your driving</h3>
        <h6>Speed limits, Road Signs, Traffic Lights</h6>
      </div>
    </div>

    <div>
      <div class="flex-center wheel-image">
        <%= image_tag "reward_phone.svg" %>
      </div>
      <div class="white text-center">
        <h3>Why track?</h3>
        <h6>Earn rewards, keep safe and save money</h6>
      </div>
    </div>

    <div>
      <div class="flex-center wheel-image">
        <%= image_tag "wheel.svg" %>
      </div>
      <div class="start-button text-center">
        <%= link_to "Let's Get Started".html_safe, new_user_session_path, :class=>"white btn btn-primary btn-round-lg white-button btn-lg start"%>
      </div>

    </div>


</div>

</div>

<script>
  $(".owl-carousel").owlCarousel({
    autoWidth:false,
  });
</script>

app/views/page/progress.html.erb
<div class="text-center">
  <br>
  <span class="white-text thin-text">PROGRESS</span><br>
  <span class="big-text"><%= @good_drives %> Drives</span><br>
  <span class="white-text mini-title">Consecutively Driven Well</span><br>
  <%= image_tag "wheel.svg", width: '40%' %><br><br>
  <div class="dark-grey-bg">
    <div class="sub-title">Offence Count</div><br>

    <div class="rows">
      <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="rows">
          <a href="/page/sign_adherence">
            <div class="col-xs-4 col-md-4 col-lg-4">
              <%= image_tag "roadsigns.svg", width: '40%' %><br><br>
            </div>
          </a>
          <a href="/page/traffic_light">
            <div class="col-xs-4 col-md-4 col-lg-4">
              <%= image_tag "trafficlight.svg", width: '25%' %><br><br>
            </div>
          </a>
          <a href="/page/speed">
            <div class="col-xs-4 col-md-4 col-lg-4">
              <%= image_tag "speed.svg", width: '50%' %><br><br>
            </div>
          </a>
        </div>
      </div>
      <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="rows">
          <a href="/page/sign_adherence" class="white-text">
            <div class="col-xs-4 col-md-4 col-lg-4">
              ROAD SIGNS
            </div>
          <a/>
          <a href="/page/traffic_light" class="white-text">
            <div class="col-xs-4 col-md-4 col-lg-4">
              TRAFFIC LIGHT
            </div>
          </a>
          <a href="/page/speed" class="white-text">
            <div class="col-xs-4 col-md-4 col-lg-4">
              SPEED
            </div>
          </a>
        </div>
      </div>
      <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="rows">
          <a href="/page/sign_adherence">
            <div class="col-xs-4 col-md-4 col-lg-4 sub-title">
              <%= @deductions["sign_adherence"] %>
            </div>
          </a>
          <a href="/page/traffic_light">
            <div class="col-xs-4 col-md-4 col-lg-4 sub-title">
              <%= @deductions["traffic_light"] %>
            </div>
          </a>
          <a href="/page/speed">
            <div class="col-xs-4 col-md-4 col-lg-4 sub-title">
              <%= @deductions["speed"] %>
            </div>
          </a>
        </div>
      </div>
    </div>
    <br>&nbsp;
  </div>
  <h3 class="white">Suggestions</h3>
  <div class="spacing"></div>
  <div class="white-box suggestion">
    Oops! Looks like you need to improve a little bit.
    <br>
    Your progress shows that you need to focus on traffic lights and sign adherence. We suggest stopping for 3 seconds at stop signs.
  </div>
  <div class="bottom-spacing"></div>
</div>

app/views/page/rewards.html.erb
<!-- Monthly score: <%= @score %> -->

<div>
  <div class="text-center reward-info">
    <div class="top-nav-with-info">
      <div class="back"></div>
      <div class="heading text-center">
        <span class="white-text thin-text">REWARDS</span>
      </div>
      <div class="back flex-center">
        <a href="/page/rewards_information"><%= image_tag "info.svg", height: '15px' %></a>
      </div>

    </div>

    <!-- <span class="white-text thin-text">REWARDS</span><br> -->
    <span class="big-text">CURRENT</span>
    <h5 class="white">1st July - 31st July</h5>
    <div class="text-center">
      <%= link_to "EARN REWARD".html_safe, page_index_path, :class=>"white btn btn-primary earn-reward white-button btn-lg start"%>
    </div>
  </div>

  <div class="flex-center container text-center evaluation white-background">
    <div class="row">
      <div class="col-xs-3 col-md-2 col-lg-2 review">
        <% if @score >= 90 %>
          <p>YOUR DRIVING: GREAT JOB!!!</p>
        <% else %>
          <p>YOUR DRIVING: OOPS WE CAN DO BETTER</p>
        <% end %>
      </div>
      <div class="col-xs-6 col-md-8 col-lg-8 flex-center face">
        <% if @score >= 90 %>
        <%= image_tag "smile.svg"%>
        <% else %>
        <%= image_tag "frown.svg"%>
        <% end %>
      </div>
      <div class="col-xs-3 col-md-2 col-lg-2 review">
        <p>DAYS LEFT: 10</p>
      </div>
    </div>
  </div>

  <div class="container text-center less-bottom-padding">
    <h2 class="white">REDEEM THESE</h2>
    <div class="row flex-center">
      <div class="col-xs-6 col-md-6 col-lg-6">
        <div class="text-center prize-reward">
          <%= link_to "x1 FUEL VOUCHER".html_safe, page_fuel_voucher_path, :class=>"white btn btn-primary prize white-button btn-lg start"%>
        </div>
      </div>
      <div class="col-xs-6 col-md-6 col-lg-6">
        <div class="text-center prize-reward">
          <%= link_to "x2 CARWASH VOUCHER".html_safe, page_carwash_voucher_path, :class=>"white btn btn-primary prize white-button btn-lg start"%>
        </div>
      </div>
    </div>
  </div>


  </div>
</div>

app/views/page/sign_adherence.html.erb
<%= render 'components/topnav', title: "SIGN ADHERENCE"%>
<%= render 'components/chart', offence_code:"sign_adherence", offence_label: "Sign Offences"  %>

app/views/page/speed.html.erb
<%= render 'components/topnav', title: "SPEED LIMITS"%>
<%= render 'components/chart', offence_code:"speed", offence_label: "Speeding Offences"  %>

app/views/page/traffic_light.html.erb
<%= render 'components/topnav', title: "TRAFFIC LIGHTS"%>
<%= render 'components/chart', offence_code:"traffic_light", offence_label: "Traffic Offences" %>

app/views/page/trip.html.erb
<%= link_to "End Trip", page_trip_summary_path %>

app/views/page/trip_progress.html.erb
<div>
  <div class="title text-center">
    <h1 class="white" id="start-title">ViBit</h1>
  </div>

  <div class="subtitle text-center">
    <h5 class="white">SHAPING TOMORROW'S DRIVERS</h5>
  </div>

  <div class="flex-center wheel-image animate-flicker">
    <%= image_tag "wheel.svg" %>
  </div>

  <div class="start-button text-center end-button">
    <%= link_to "End Trip".html_safe, page_trip_summary_path, :class=>"white btn btn-primary white-button btn-round-lg btn-lg start"%>
  </div>

</div>

app/views/page/trip_summary.html.erb
<div class="full-white-bg">
  <div class="title text-center">
    <% if @score > 90 %>
      <h1 id="start-title">Great Drive</h1>
    <% else %>
      <h1 id="start-title">Oops!</h1>
    <% end %>
  </div>

  <div class="subtitle text-center orange">
    <h5 ><%= Time.now.strftime("%d/%m/%Y %H:%M") %></h5>
  </div>

  <div class="flex-center driving-review">
    <% if @score > 90 %>
      <%= image_tag "good_driving.svg" %>
    <% else %>
      <%= image_tag "bad_driving.svg" %>
    <% end %>
  </div>

  <div class="measures orange text-center">
    Total Distance: <%= @distance.to_i %> <br>
    Time: <%= @time %>
  </div>

  <div class="flex-center text-center">
    <div>
      <div class="violation">
        <%= image_tag "roadsigns_orange.svg" %>
      </div>
      <%= @counter["sign_adherence"] %>
    </div>

  <div>
    <div class="violation">
      <%= image_tag "trafficlight_orange.svg" %>
    </div>
    <%= @counter["traffic_light"] %>
  </div>

  <div>
    <div class="violation">
      <%= image_tag "speed_orange.svg" %>
    </div>
    <%= @counter["speeding"] %>
  </div>

  </div>

  <div class="continue-button text-center button-padding">
    <%= link_to "CONTINUE".html_safe, page_progress_path, :class=>"btn orange-button btn-round-lg btn-lg continue"%>
  </div>

  <%= render 'components/map' %>

</div>